# ------------------------------------------------------- #
#                 Monitoring-Config
# ------------------------------------------------------- #
general:
  version: v1.0.5
  debug_level: info
  check_cycle_in_minutes: 10
  snmp_password: Snmp_Password
  discord_webhook: https://WebhookUrl/
  discord_username: YourBotsName
  use_gotify: false
  gotify_url: https://YourUrl
  gotify_port: 443
  gotify_token: YourApiKey

# ------------------------------------------------------- #
#                        InfluxDB
# ------------------------------------------------------- #
# This has not been added yet but is on my to-do list.
influx:
  connection_string: Stwing
  token: token
  org: Group
  bucket: Buget

# ------------------------------------------------------- #
#                        Hosts
# ------------------------------------------------------- #
clients:
  111.222.333.444: {hostname: Host-name1, offline: false}
  111.222.333.445: {hostname: Host-name2, offline: false}
  111.222.333.456: {hostname: Host-name3, offline: false}
